# Usamos una imagen base de Nginx, un servidor web ligero.
FROM nginx:alpine

# Copiamos el archivo index.html en la ubicación predeterminada de Nginx para archivos estáticos.
COPY index.html /usr/share/nginx/html/index.html
